### ISSUE TITLE
release tgz is missing for 0.43.2

### ISSUE THREAD

**Issue by czanik** [buytenh/ivykis#35]
I wanted to build a Fedora package for testing, but could not find a release tgz for 0.43.2 on sourceforge.

**Comment by buytenh** [comment]
Oops, I forgot.  Should be fixed now.

**Comment by czanik** [comment]
Thanks! Packaged and tested on Fedora, and this time I had no issues. Also tested on FreeBSD, without any problems. I'll update the official Fedora package in the coming days.
